language: r

env:
  - LINTR_COMMENT_BOT=false

matrix:
  include:
  os:
    - linux
    - osx
    - windows
  r:
    - oldrel
    - release
    - devel

r_packages:
  - covr
  - lintr

addons:
  apt:
    packages:
      - libnlopt-dev

after_success:
  - travis_wait 30 Rscript -e 'covr::codecov()'
