language: r

matrix:
  include:
    os:
      - windows
    r:
      - oldrel
      - release
      - devel

r_packages:
  - covr
  - lintr

addons:
  apt:
    packages:
      - libnlopt-dev

after_success:
  - travis_wait 30 Rscript -e 'covr::codecov()'
